export const SITE = {
  website: "https://gabrielregis.com",
  author: "Gabriel Regis",
  profile: "https://gabrielregis.com",
  desc: "A minimal, responsive and SEO-friendly Astro blog theme.",
  title: "MindCache",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 10,
  postPerPage: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/satnaing/astro-paper/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "pt",
  timezone: "America/Sao_Paulo",
} as const;
